// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjadsivcrvtsmdizftbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYWRzaXZjcnZ0c21kaXpmdGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzgyMzEsImV4cCI6MjA3MjY1NDIzMX0.64uVnqcoSvesurdGoVUr0slbaDQyr76dRrvqMI9fPSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});